
# lab06_hello_dag.py  --  AUTO-GENERATED by lab06_airflow.ipynb
#
# DAG = Directed Acyclic Graph: a set of tasks connected by dependency arrows.
# 'Directed'  = arrows go one way (no loops allowed)
# 'Acyclic'   = no task depends on itself (no cycles)
# 'Graph'     = a network of nodes (tasks) and edges (dependencies)

from datetime import datetime
from airflow import DAG
from airflow.operators.python import PythonOperator   # PythonOperator: run any Python function as a task
from airflow.operators.bash import BashOperator       # BashOperator:   run a shell command as a task

# 'with DAG(...) as dag:' is a context manager.
# Every operator created INSIDE this block is automatically registered to this DAG.
with DAG(
    dag_id='lab06_hello_dag',          # unique name shown in the Airflow UI DAG list
    schedule_interval=None,            # None = manual trigger only; no automatic schedule
    start_date=datetime(2026, 4, 1),   # Airflow requires a start_date to know when runs are valid
    catchup=False,                     # False = don't create runs for all past dates; start fresh
    tags=['lab06', 'intro'],           # tags appear as filter chips in the Airflow UI
) as dag:

    def greet(**context):              # **context = dict of Airflow metadata Airflow passes in at runtime
        ds = context['ds']             # 'ds' = execution date string in YYYY-MM-DD format
        print(f'Hello from Airflow! Execution date: {ds}')   # this text appears in the task log
        return {'greeted': True, 'date': ds}                 # return value is auto-stored as XCom

    t1 = PythonOperator(
        task_id='python_greet',        # task_id must be unique within the DAG
        python_callable=greet,         # pass the function object (no parentheses = don't call it now)
    )

    t2 = BashOperator(
        task_id='bash_echo',
        bash_command='echo "Bash task ran on {{ ds }}"',   # {{ ds }} is a Jinja2 template filled in at runtime
    )

    t1 >> t2   # >> = task dependency: t1 must SUCCEED before t2 is allowed to start
