
# lab06_taskflow_demo.py  --  AUTO-GENERATED by lab06_airflow.ipynb
#
# TaskFlow API: use @dag and @task decorators instead of manually creating operators.
# XCom: when a @task function returns a value, Airflow automatically stores it.
# The next @task receives it as a function argument — no manual xcom_push/pull needed.

from airflow.decorators import dag, task   # @dag = mark a function as a DAG; @task = mark a function as a task
from datetime import datetime

@dag(
    dag_id='lab06_taskflow_demo',
    schedule_interval=None,
    start_date=datetime(2026, 4, 1),
    catchup=False,
    tags=['lab06', 'taskflow'],
)
def taskflow_demo():
    'Demonstrate the TaskFlow API: extract -> transform -> load with automatic XCom.'

    @task                            # @task = this function becomes an Airflow task automatically
    def extract() -> dict:           # return type hint (dict) tells Airflow how to serialize the XCom value
        'Simulate reading file metadata from an upstream system.'
        return {'rows': 1000, 'source': 'minio', 'date': '2026-04-27'}  # this dict is auto-stored as XCom

    @task
    def transform(raw: dict) -> dict:   # raw = the dict returned by extract() — Airflow pulls XCom automatically
        'Filter and enrich: compute success/failure row counts.'
        raw['successful_rows'] = int(raw['rows'] * 0.75)           # 75% of transactions succeed
        raw['failed_rows']     = raw['rows'] - raw['successful_rows']  # the rest failed
        return raw                                                   # pass enriched dict to next task via XCom

    @task
    def load(data: dict):    # data = the dict returned by transform() — again pulled from XCom automatically
        'Log final stats. In production this would write to a database or Delta table.'
        print(f'[LOAD] Date             : {data["date"]}')
        print(f'[LOAD] Successful rows  : {data["successful_rows"]}/{data["rows"]}')
        print(f'[LOAD] Failed rows      : {data["failed_rows"]}/{data["rows"]}')

    # Call the task functions as if they are normal Python functions.
    # Airflow infers the dependencies from the call order: extract -> transform -> load.
    raw  = extract()
    proc = transform(raw)   # 'raw' is an XCom reference, not the actual dict yet
    load(proc)

dag_instance = taskflow_demo()   # calling the @dag-decorated function registers it with Airflow
