
# lab06_branch_xcom.py  --  AUTO-GENERATED by lab06_airflow.ipynb

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator, BranchPythonOperator   # BranchPythonOperator = conditional fork
from airflow.operators.dummy import DummyOperator   # DummyOperator = placeholder task that does nothing (used for join points)

with DAG(
    dag_id='lab06_branch_xcom',
    schedule_interval=None,
    start_date=datetime(2026, 4, 1),
    catchup=False,
    default_args={                     # default_args = settings applied to ALL tasks in this DAG
        'retries': 2,                  # retry a failed task up to 2 times before marking it as failed
        'retry_delay': timedelta(minutes=2),   # wait 2 minutes between retry attempts
        'email_on_failure': False,     # don't try to send email (we haven't configured a mail server)
    },
    tags=['lab06', 'xcom', 'branch'],
) as dag:

    def count_rows(**context):
        'Count ingested rows and push the result to XCom so other tasks can read it.'
        ti        = context['task_instance']   # task_instance = the running task object
        row_count = 1500                       # in production: query MinIO or a database

        # xcom_push stores a key-value pair that any downstream task in the same DAG run can read
        ti.xcom_push(key='row_count',  value=row_count)
        ti.xcom_push(key='quality_ok', value=row_count > 500)   # True if more than 500 rows
        print(f'Row count: {row_count}')

    def choose_branch(**context):
        'Read the row count from XCom and decide which downstream path to take.'
        ti    = context['ti']   # ti = shorthand alias for task_instance
        count = ti.xcom_pull(task_ids='count_rows', key='row_count')  # pull the value pushed by count_rows
        print(f'Branching on count={count}')
        # The return value is the task_id (or list of task_ids) that should run next.
        # All other downstream tasks are automatically SKIPPED.
        return 'high_volume' if count > 1000 else 'low_volume'

    def log_xcom(**context):
        'Demonstrate xcom_pull: read and print both values pushed by count_rows.'
        ti   = context['ti']
        rows = ti.xcom_pull(task_ids='count_rows', key='row_count')
        ok   = ti.xcom_pull(task_ids='count_rows', key='quality_ok')
        print(f'[LOG] row_count={rows}, quality_ok={ok}')

    # Create task objects from the functions above
    count  = PythonOperator(task_id='count_rows',   python_callable=count_rows)
    log    = PythonOperator(task_id='log_xcom',     python_callable=log_xcom)

    # BranchPythonOperator: runs choose_branch() and skips all branches NOT returned
    branch = BranchPythonOperator(task_id='branch', python_callable=choose_branch)

    high   = DummyOperator(task_id='high_volume')   # placeholder for 'send alert: high volume'
    low    = DummyOperator(task_id='low_volume')    # placeholder for 'send alert: low volume'

    # 'none_failed_min_one_success' = this task runs as long as at least one upstream task succeeded
    # (needed because the branch operator skips one path, which would otherwise block the join)
    join   = DummyOperator(task_id='join', trigger_rule='none_failed_min_one_success')

    # Define the dependency graph:
    count >> log >> branch >> [high, low]   # branch fans out to both; only one will actually run
    high  >> join                           # both paths converge at join
    low   >> join
