
# lab06_spark_etl.py  --  AUTO-GENERATED by lab06_airflow.ipynb
#
# Full ETL pipeline:
#   wait_for_csv -> spark_transform -> validate_output -> branch -> notify_success / notify_failure

from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
from airflow.providers.amazon.aws.sensors.s3 import S3KeySensor   # S3KeySensor = wait for a file to appear in S3/MinIO
from airflow.operators.python import PythonOperator, BranchPythonOperator
from airflow.operators.dummy import DummyOperator

# Spark config dict passed to the SparkSubmitOperator
# These settings tell the Spark cluster how to connect to MinIO
SPARK_CONF = {
    'spark.hadoop.fs.s3a.endpoint':          'http://minio:9000',
    'spark.hadoop.fs.s3a.access.key':        'admin',
    'spark.hadoop.fs.s3a.secret.key':        'bigdata123',
    'spark.hadoop.fs.s3a.path.style.access': 'true',
    'spark.hadoop.fs.s3a.impl':              'org.apache.hadoop.fs.s3a.S3AFileSystem',
}

with DAG(
    dag_id='lab06_spark_etl',
    schedule_interval='0 2 * * *',    # cron expression: run at 02:00 every day
    start_date=datetime(2026, 4, 1),
    catchup=False,
    max_active_runs=1,                # prevent overlapping runs if a run is slow
    default_args={
        'owner': 'innocent',
        'retries': 2,
        'retry_delay': timedelta(minutes=5),
        'email_on_failure': False,
        'sla': timedelta(hours=3),    # SLA = Service Level Agreement; alert if task exceeds 3 hours
    },
    tags=['lab06', 'spark', 'etl', 'finance'],
) as dag:

    # Task 1: wait for the input file to appear in MinIO before starting the Spark job
    # {{ ds }} is a Jinja template that Airflow fills in with the execution date (YYYY-MM-DD)
    wait_for_file = S3KeySensor(
        task_id='wait_for_csv',
        bucket_name='warehouse',                             # the MinIO bucket to check
        bucket_key='raw/transactions/{{ ds }}/data.csv',    # the specific key (path) to wait for
        aws_conn_id='minio_s3',         # Airflow Connection ID — configure in Admin -> Connections
        poke_interval=30,               # check every 30 seconds
        timeout=60 * 30,                # give up after 30 minutes
        mode='poke',                    # 'poke' = keep the worker slot occupied while waiting
    )

    # Task 2: submit the PySpark script to the Spark cluster
    spark_transform = SparkSubmitOperator(
        task_id='spark_transform',
        application='/opt/airflow/spark_jobs/transform_transactions.py',  # script path in the Airflow container
        conn_id='spark_default',         # Airflow Connection for Spark — configure in Admin -> Connections
        application_args=['--date', '{{ ds }}'],  # command-line args passed to the script
        conf=SPARK_CONF,                 # Spark config overrides
        num_executors=1,                 # 1 executor is enough for our small dataset
        executor_memory='512m',          # memory per executor
        driver_memory='256m',            # memory for the driver process
    )

    def validate_output(ds=None, **context):
        'Check that the Spark job actually wrote output files to MinIO.'
        import boto3
        s3 = boto3.client('s3', endpoint_url='http://minio:9000',
                          aws_access_key_id='admin', aws_secret_access_key='bigdata123')
        prefix = f'processed/transactions/date={ds}/'   # the output path the Spark job writes to
        resp   = s3.list_objects_v2(Bucket='warehouse', Prefix=prefix)
        files  = resp.get('Contents', [])               # list of file metadata dicts

        if not files:   # no files found — Spark job must have failed
            raise ValueError(f'No output files at s3a://warehouse/{prefix}')

        total_bytes = sum(f['Size'] for f in files)     # total bytes written
        print(f'[VALIDATE] {len(files)} files, {total_bytes} bytes at {prefix}')

        ti = context['ti']                              # task_instance object
        ti.xcom_push(key='file_count', value=len(files))  # push file count for the branch task to read

    validate = PythonOperator(
        task_id='validate_output',
        python_callable=validate_output,
        provide_context=True,   # provide_context=True passes the Airflow context dict to the function
    )

    def branch_on_validation(**context):
        'Read the file count XCom and decide which notification path to take.'
        ti = context['ti']
        fc = ti.xcom_pull(task_ids='validate_output', key='file_count')   # pull the value we pushed above
        return 'notify_success' if (fc and fc > 0) else 'notify_failure'  # return the task_id to run next

    branch         = BranchPythonOperator(task_id='branch',          python_callable=branch_on_validation)
    notify_success = DummyOperator(task_id='notify_success')   # in production: send Slack/email success alert
    notify_failure = DummyOperator(task_id='notify_failure')   # in production: page on-call engineer

    # Wire up the pipeline
    wait_for_file >> spark_transform >> validate >> branch
    branch >> [notify_success, notify_failure]
